# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(default=None, max_length=250)),
                ('status', models.CharField(choices=[('Done', 'Done'), ('In Progress', 'In Progress'), ('Not done', 'Not done')], max_length=20)),
                ('datetime', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dashboard.User'),
        ),
    ]
